title: SignalTrove
url: https://signaltrove.github.io
baseurl: ""
timezone: Asia/Seoul
markdown: kramdown

# 테마를 쓰고 있다면 남겨도 되고(예: minima), 없어도 됩니다.
# theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

collections:
  pages:
    output: true
